/* Generated by Yosys 0.22+37 (git sha1 be1a12595, gcc 12.2.0 -march=x86-64 -mtune=generic -O2 -fno-plt -fexceptions -fstack-clash-protection -fcf-protection -fPIC -Os) */

(* \amaranth.hierarchy  = "top" *)
(* top =  1  *)
(* generator = "Amaranth" *)
module top(mode, o, clk, rst, tap);
  reg \$auto$verilog_backend.cc:2083:dump_module$1  = 0;
  (* src = "/home/emil/pulls/tt02-verilog-demo/src/chase_the_beat.py:69" *)
  wire [7:0] \$1 ;
  (* src = "/home/emil/pulls/amaranth/amaranth/hdl/ir.py:527" *)
  input clk;
  wire clk;
  (* src = "/home/emil/pulls/tt02-verilog-demo/src/chase_the_beat.py:58" *)
  input mode;
  wire mode;
  (* src = "/home/emil/pulls/tt02-verilog-demo/src/chase_the_beat.py:57" *)
  output [7:0] o;
  reg [7:0] o = 8'h00;
  (* src = "/home/emil/pulls/tt02-verilog-demo/src/chase_the_beat.py:57" *)
  reg [7:0] \o$next ;
  (* src = "/home/emil/pulls/amaranth/amaranth/hdl/ir.py:527" *)
  input rst;
  wire rst;
  (* src = "/home/emil/pulls/tt02-verilog-demo/src/chase_the_beat.py:56" *)
  input tap;
  wire tap;
  assign \$1  = ~ (* src = "/home/emil/pulls/tt02-verilog-demo/src/chase_the_beat.py:69" *) o;
  always @(posedge clk)
    o <= \o$next ;
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$1 ) begin end
    \o$next  = \$1 ;
    (* src = "/home/emil/pulls/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \o$next  = 8'h00;
    endcase
  end
endmodule
